version: '3'

services:
  psql:
    build:
      context: .
      dockerfile: ./docker/postgresql/Dockerfile
    ports:
      - 5432:5432

  app:
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - 8080:8080
    depends_on:
      - psql