spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_library
    username: postgres
    password: pass
    initialization-mode: always

  data:
    mongodb:
      host: localhost
      port: 27017
      database: books_reserve

  batch:
    job:
      enabled: false
    initialize-schema: always

#  jpa:
#    generate-ddl: true

logging:
  level:
    root: info

