spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_library
    username: postgres
    password: pass
    initialization-mode: always

#  jpa:
#    generate-ddl: true

logging:
  level:
    root: info

